using System.Text;
using System.Xml.Linq;
using XamlSub.Models;

namespace XamlSub.Services;

public sealed class WriteBackService
{
    private readonly XamlDocumentService _xaml;
    private readonly CSharpEventService _csharp;

    public WriteBackService(XamlDocumentService xaml, CSharpEventService csharp)
    {
        _xaml = xaml;
        _csharp = csharp;
    }

    public async Task WriteXamlOnlyAsync(GridDocument model, CancellationToken cancellationToken = default)
    {
        model.Normalize();
        var original = await ReadTextFileAsync(model.FilePath, cancellationToken);
        var newXaml = NormalizeNewlines(_xaml.Serialize(model), DetectNewline(original.Text));
        await CommitPairAsync(model.FilePath, newXaml, null, null, original.Encoding, null, cancellationToken);
        model.OriginalXamlText = newXaml;
        model.IsDirty = false;
    }

    public async Task WriteAsync(GridDocument model, GridDocument? baseline = null, CancellationToken cancellationToken = default)
    {
        model.Normalize();

        var xamlOriginal = await ReadTextFileAsync(model.FilePath, cancellationToken);
        var xamlNewline = DetectNewline(xamlOriginal.Text);

        // Do not overwrite a class identity repaired by broad-save mode. Only restore the
        // on-disk value when the in-memory model is actually empty.
        var diskXClass = ExtractXClass(xamlOriginal.Text);
        if (string.IsNullOrWhiteSpace(model.XClass) && !string.IsNullOrWhiteSpace(diskXClass))
            model.XClass = diskXClass;

        var codeBehindPath = model.CodeBehindPath;
        var hasCodeBehind = codeBehindPath is not null && File.Exists(codeBehindPath);
        string? newCs = null;
        FileText? csOriginal = null;

        if (hasCodeBehind)
        {
            // The save-mode policy has already selected the same-name .xaml.cs.
            // Do not perform another association check. Always repair x:Class from the
            // actual code-behind when possible, including replacing a stale simple name
            // like "MainWindow" with its real namespaced class identity.
            var repairedClass = ProjectLocator.GetBroadSaveClassIdentity(model.FilePath, codeBehindPath!, model.XClass);
            if (!string.IsNullOrWhiteSpace(repairedClass))
                model.XClass = repairedClass;

            EnsureWindowRootName(model);
            PrepareEventMetadata(model);

            csOriginal = await ReadTextFileAsync(codeBehindPath!, cancellationToken);
            var csNewline = DetectNewline(csOriginal.Text);
            var currentCs = csOriginal.Text;

            newCs = _csharp.EnsureCodeBehindClass(currentCs, model.XClass!, model.RootTypeName);

            var oldById = baseline?.Nodes.ToDictionary(n => n.Id) ?? new Dictionary<Guid, ControlNode>();
            foreach (var node in model.Nodes)
            {
                oldById.TryGetValue(node.Id, out var old);
                var oldEvent = old?.EventWasAutoGenerated == true ? old.EventName : null;
                var newEvent = node.EventName;
                if (string.IsNullOrWhiteSpace(newEvent))
                    continue;

                if (oldEvent is not null && !string.Equals(oldEvent, newEvent, StringComparison.Ordinal))
                    newCs = RenameGeneratedHandler(newCs, node, oldEvent, newEvent, model.XClass, model.Framework);
                else
                    newCs = _csharp.EnsureEventHandler(newCs, node, newEvent, model.XClass, model.Framework);
            }

            if (string.Equals(model.RootTypeName, "Window", StringComparison.Ordinal) && !string.IsNullOrWhiteSpace(model.RootXName))
                newCs = _csharp.EnsureLoadedHandler(newCs, model.RootXName, "Window_Loaded", model.XClass, model.Framework);

            newCs = NormalizeNewlines(newCs, csNewline);
        }

        // XAML serialization always writes EventName as a string attribute value and keeps
        // the repaired x:Class from the in-memory model.
        var newXaml = NormalizeNewlines(_xaml.Serialize(model), xamlNewline);
        await CommitPairAsync(
            model.FilePath,
            newXaml,
            codeBehindPath,
            newCs,
            xamlOriginal.Encoding,
            csOriginal?.Encoding,
            cancellationToken);

        model.OriginalXamlText = newXaml;
        model.IsDirty = false;
    }

    private string RenameGeneratedHandler(string source, ControlNode node, string oldEventName, string newEventName, string? targetClassName, XamlFrameworkKind framework)
    {
        if (string.IsNullOrWhiteSpace(oldEventName) || string.IsNullOrWhiteSpace(newEventName))
            return source;

        var pattern = $@"\b{System.Text.RegularExpressions.Regex.Escape(oldEventName)}\b";
        var renamed = System.Text.RegularExpressions.Regex.Replace(source, pattern, newEventName);
        return _csharp.EnsureEventHandler(renamed, node, newEventName, targetClassName, framework);
    }

    public static Task CommitRawPairAsync(string xamlPath, string newXaml, string? csPath, string? newCs, CancellationToken cancellationToken = default)
        => CommitPairAsync(xamlPath, newXaml, csPath, newCs, null, null, cancellationToken);

    private static void EnsureWindowRootName(GridDocument model)
    {
        if (!string.Equals(model.RootTypeName, "Window", StringComparison.Ordinal) || !string.IsNullOrWhiteSpace(model.RootXName))
            return;

        var usedNames = model.Nodes
            .Where(n => !string.IsNullOrWhiteSpace(n.XName))
            .Select(n => n.XName!)
            .ToHashSet(StringComparer.Ordinal);

        var index = 0;
        var candidate = "ContentRoot";
        while (!usedNames.Add(candidate))
            candidate = $"ContentRoot{++index}";
        model.RootXName = candidate;
    }

    private static void PrepareEventMetadata(GridDocument model)
    {
        var usedNames = model.Nodes
            .Where(n => !string.IsNullOrWhiteSpace(n.XName))
            .Select(n => n.XName!)
            .ToHashSet(StringComparer.Ordinal);

        foreach (var node in model.Nodes)
        {
            if (string.IsNullOrWhiteSpace(node.XName))
            {
                var baseName = string.IsNullOrWhiteSpace(node.TypeName) ? "Control" : node.TypeName;
                var index = 1;
                var candidate = baseName + index;
                while (!usedNames.Add(candidate))
                    candidate = baseName + (++index);
                node.XName = candidate;
            }

            if (string.IsNullOrWhiteSpace(node.EventName) || node.EventWasAutoGenerated)
            {
                node.EventKind = node.SupportsClick ? "Click" : "Tapped";
                node.EventName = node.XName + "_" + node.EventKind;
                node.EventWasAutoGenerated = true;
            }
            else if (node.EventKind is not ("Click" or "Tapped"))
            {
                node.EventKind = node.SupportsClick ? "Click" : "Tapped";
            }
        }
    }

    private static async Task CommitPairAsync(
        string xamlPath,
        string newXaml,
        string? csPath,
        string? newCs,
        Encoding? xamlEncoding,
        Encoding? csEncoding,
        CancellationToken cancellationToken)
    {
        var oldXaml = await ReadTextFileAsync(xamlPath, cancellationToken);
        var oldCs = csPath is not null && File.Exists(csPath)
            ? await ReadTextFileAsync(csPath, cancellationToken)
            : null;

        var xamlTemp = xamlPath + ".designer-tmp";
        var csTemp = csPath is null ? null : csPath + ".designer-tmp";

        try
        {
            await WriteTextFileAsync(xamlTemp, newXaml, xamlEncoding ?? oldXaml.Encoding, cancellationToken);
            if (csTemp is not null && newCs is not null)
                await WriteTextFileAsync(csTemp, newCs, csEncoding ?? oldCs?.Encoding, cancellationToken);

            File.Move(xamlTemp, xamlPath, true);
            if (csPath is not null && csTemp is not null && newCs is not null)
                File.Move(csTemp, csPath, true);
        }
        catch
        {
            try { if (File.Exists(xamlTemp)) File.Delete(xamlTemp); } catch { }
            try { if (csTemp is not null && File.Exists(csTemp)) File.Delete(csTemp); } catch { }
            try { await WriteTextFileAsync(xamlPath, oldXaml.Text, oldXaml.Encoding, cancellationToken); } catch { }
            if (csPath is not null && oldCs is not null)
            {
                try { await WriteTextFileAsync(csPath, oldCs.Text, oldCs.Encoding, cancellationToken); } catch { }
            }
            throw;
        }
    }

    private sealed record FileText(string Text, Encoding Encoding);

    private static async Task<FileText> ReadTextFileAsync(string path, CancellationToken cancellationToken)
    {
        var bytes = await File.ReadAllBytesAsync(path, cancellationToken);
        var (encoding, offset) = DetectEncoding(bytes);
        var text = encoding.GetString(bytes, offset, bytes.Length - offset);
        return new FileText(text, encoding);
    }

    private static async Task WriteTextFileAsync(string path, string text, Encoding? encoding, CancellationToken cancellationToken)
    {
        var actualEncoding = encoding ?? new UTF8Encoding(false);
        await File.WriteAllTextAsync(path, text, actualEncoding, cancellationToken);
    }

    private static (Encoding Encoding, int Offset) DetectEncoding(byte[] bytes)
    {
        if (bytes.Length >= 4 && bytes[0] == 0x00 && bytes[1] == 0x00 && bytes[2] == 0xFE && bytes[3] == 0xFF)
            return (new UTF32Encoding(true, true), 4);
        if (bytes.Length >= 4 && bytes[0] == 0xFF && bytes[1] == 0xFE && bytes[2] == 0x00 && bytes[3] == 0x00)
            return (new UTF32Encoding(false, true), 4);
        if (bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF)
            return (new UTF8Encoding(true), 3);
        if (bytes.Length >= 2 && bytes[0] == 0xFE && bytes[1] == 0xFF)
            return (new UnicodeEncoding(true, true), 2);
        if (bytes.Length >= 2 && bytes[0] == 0xFF && bytes[1] == 0xFE)
            return (new UnicodeEncoding(false, true), 2);
        return (new UTF8Encoding(false), 0);
    }

    private static string DetectNewline(string text)
        => text.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";

    private static string NormalizeNewlines(string text, string newline)
    {
        var normalized = text.Replace("\r\n", "\n").Replace('\r', '\n');
        return newline == "\n" ? normalized : normalized.Replace("\n", newline);
    }

    private static string? ExtractXClass(string xamlText)
    {
        try
        {
            var doc = System.Xml.Linq.XDocument.Parse(xamlText, System.Xml.Linq.LoadOptions.PreserveWhitespace);
            var root = doc.Root;
            if (root is null) return null;
            XNamespace x = "http://schemas.microsoft.com/winfx/2006/xaml";
            return (string?)root.Attribute(x + "Class");
        }
        catch
        {
            return null;
        }
    }
}
