using XamlSub.Models;

namespace XamlSub.Services;

public sealed class WriteBackService
{
    private readonly XamlDocumentService _xaml;
    private readonly CSharpEventService _csharp;

    public WriteBackService(XamlDocumentService xaml, CSharpEventService csharp)
    {
        _xaml = xaml;
        _csharp = csharp;
    }

    public async Task WriteXamlOnlyAsync(GridDocument model, CancellationToken cancellationToken = default)
    {
        model.Normalize();
        var newXaml = _xaml.Serialize(model);
        await CommitPairAsync(model.FilePath, newXaml, null, null, cancellationToken);
        model.OriginalXamlText = newXaml;
        model.IsDirty = false;
    }

    public async Task WriteAsync(GridDocument model, GridDocument? baseline = null, CancellationToken cancellationToken = default)
    {
        var codeBehindPath = model.CodeBehindPath;
        var hasCodeBehind = codeBehindPath is not null && File.Exists(codeBehindPath);
        string? newCs = null;

        if (hasCodeBehind)
        {
            EnsureWindowRootName(model);
            PrepareEventMetadata(model);
            if (string.IsNullOrWhiteSpace(model.XClass))
                throw new InvalidOperationException("没有找到可用于 code-behind 的 class 名称。");

            var currentCs = await File.ReadAllTextAsync(codeBehindPath!, cancellationToken);
            newCs = _csharp.EnsureCodeBehindClass(currentCs, model.XClass!, model.RootTypeName);
            var oldById = baseline?.Nodes.ToDictionary(n => n.Id) ?? new Dictionary<Guid, ControlNode>();
            foreach (var node in model.Nodes)
            {
                oldById.TryGetValue(node.Id, out var old);
                var oldEvent = old?.EventWasAutoGenerated == true ? old.EventName : null;
                var newEvent = node.EventName;
                if (string.IsNullOrWhiteSpace(newEvent))
                    continue;

                if (oldEvent is not null && !string.Equals(oldEvent, newEvent, StringComparison.Ordinal))
                    newCs = RenameGeneratedHandler(newCs, node, oldEvent, newEvent, model.XClass);
                else
                    newCs = _csharp.EnsureEventHandler(newCs, node, newEvent, model.XClass);
            }

            if (string.Equals(model.RootTypeName, "Window", StringComparison.Ordinal) && !string.IsNullOrWhiteSpace(model.RootXName))
                newCs = _csharp.EnsureLoadedHandler(newCs, model.RootXName, "Window_Loaded", model.XClass);
        }

        // Serialize after broad-save mode has supplied an x:Class identity so the generated
        // XAML and code-behind stay associated with each other.
        var newXaml = _xaml.Serialize(model);
        await CommitPairAsync(model.FilePath, newXaml, model.CodeBehindPath, newCs, cancellationToken);
        model.OriginalXamlText = newXaml;
        model.IsDirty = false;
    }

    private string RenameGeneratedHandler(string source, ControlNode node, string oldEventName, string newEventName, string? targetClassName)
    {
        // Keep this rename independent of Roslyn token-replacement APIs so it also works with
        // older Microsoft.CodeAnalysis versions used by some developer environments.
        if (string.IsNullOrWhiteSpace(oldEventName) || string.IsNullOrWhiteSpace(newEventName))
            return source;

        var pattern = $@"\b{System.Text.RegularExpressions.Regex.Escape(oldEventName)}\b";
        var renamed = System.Text.RegularExpressions.Regex.Replace(source, pattern, newEventName);
        return _csharp.EnsureEventHandler(renamed, node, newEventName, targetClassName);
    }

    public static Task CommitRawPairAsync(string xamlPath, string newXaml, string? csPath, string? newCs, CancellationToken cancellationToken = default)
        => CommitPairAsync(xamlPath, newXaml, csPath, newCs, cancellationToken);

    private static void EnsureWindowRootName(GridDocument model)
    {
        if (!string.Equals(model.RootTypeName, "Window", StringComparison.Ordinal) || !string.IsNullOrWhiteSpace(model.RootXName))
            return;

        var usedNames = model.Nodes
            .Where(n => !string.IsNullOrWhiteSpace(n.XName))
            .Select(n => n.XName!)
            .ToHashSet(StringComparer.Ordinal);

        var index = 0;
        var candidate = "ContentRoot";
        while (!usedNames.Add(candidate))
            candidate = $"ContentRoot{++index}";
        model.RootXName = candidate;
    }

    private static void PrepareEventMetadata(GridDocument model)
    {
        var usedNames = model.Nodes
            .Where(n => !string.IsNullOrWhiteSpace(n.XName))
            .Select(n => n.XName!)
            .ToHashSet(StringComparer.Ordinal);

        foreach (var node in model.Nodes)
        {
            if (string.IsNullOrWhiteSpace(node.XName))
            {
                var baseName = string.IsNullOrWhiteSpace(node.TypeName) ? "Control" : node.TypeName;
                var index = 1;
                var candidate = baseName + index;
                while (!usedNames.Add(candidate))
                    candidate = baseName + (++index);
                node.XName = candidate;
            }

            if (string.IsNullOrWhiteSpace(node.EventName) || node.EventWasAutoGenerated)
            {
                node.EventKind = node.SupportsClick ? "Click" : "Tapped";
                node.EventName = node.XName + "_" + node.EventKind;
                node.EventWasAutoGenerated = true;
            }
        }
    }

    private static async Task CommitPairAsync(string xamlPath, string newXaml, string? csPath, string? newCs, CancellationToken cancellationToken)
    {
        var oldXaml = await File.ReadAllTextAsync(xamlPath, cancellationToken);
        var oldCs = csPath is not null && File.Exists(csPath) ? await File.ReadAllTextAsync(csPath, cancellationToken) : null;
        var xamlTemp = xamlPath + ".designer-tmp";
        var csTemp = csPath is null ? null : csPath + ".designer-tmp";
        try
        {
            await File.WriteAllTextAsync(xamlTemp, newXaml, cancellationToken);
            if (csTemp is not null && newCs is not null)
                await File.WriteAllTextAsync(csTemp, newCs, cancellationToken);
            File.Move(xamlTemp, xamlPath, true);
            if (csPath is not null && csTemp is not null && newCs is not null)
                File.Move(csTemp, csPath, true);
        }
        catch
        {
            try { if (File.Exists(xamlTemp)) File.Delete(xamlTemp); } catch { }
            try { if (csTemp is not null && File.Exists(csTemp)) File.Delete(csTemp); } catch { }
            try { await File.WriteAllTextAsync(xamlPath, oldXaml, cancellationToken); } catch { }
            if (csPath is not null && oldCs is not null)
            {
                try { await File.WriteAllTextAsync(csPath, oldCs, cancellationToken); } catch { }
            }
            throw;
        }
    }
}
