namespace XamlSub.Models;

public sealed class ControlNode
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public int? SourceKey { get; set; }
    public string? NamespaceUri { get; set; }
    public string TypeName { get; set; } = "Button";
    public string? XName { get; set; }
    public string? Content { get; set; }
    public int Row { get; set; }
    public int Column { get; set; }
    public int RowSpan { get; set; } = 1;
    public int ColumnSpan { get; set; } = 1;
    public string? Width { get; set; }
    public string? Height { get; set; }
    public string? HorizontalAlignment { get; set; }
    public string? VerticalAlignment { get; set; }
    public double OffsetX { get; set; }
    public double OffsetY { get; set; }
    public bool DesignerPositionCustomized { get; set; }
    public string? Dock { get; set; }
    public string? EventName { get; set; }
    public string? EventKind { get; set; }
    public bool EventWasAutoGenerated { get; set; }

    /// <summary>Supported editable attributes beyond the core layout fields.</summary>
    public Dictionary<string, string> Properties { get; set; } = new(StringComparer.Ordinal);

    /// <summary>Attributes the designer preserves but does not expose in the property panel.</summary>
    public Dictionary<string, string> ExtraAttributes { get; set; } = new(StringComparer.Ordinal);

    public bool SupportsClick => new HashSet<string>(StringComparer.Ordinal)
    {
        "Button", "HyperlinkButton", "ToggleButton", "RepeatButton", "CheckBox", "RadioButton"
    }.Contains(TypeName);

    public bool SupportsTapped => true;
    public string? DerivedEventName => string.IsNullOrWhiteSpace(XName) ? null : XName + "_" + DerivedEventKind;
    public string DerivedEventKind => SupportsClick ? "Click" : "Tapped";

    public bool IsPropertyEnabled(string propertyName)
    {
        switch (propertyName)
        {
            case "Source":
            case "Stretch":
                return TypeName == "Image";
            case "PlaceholderText":
                return TypeName == "TextBox" || TypeName == "ComboBox" || TypeName == "AutoSuggestBox";
            case "Header":
                return TypeName == "TextBox" || TypeName == "PasswordBox" || TypeName == "NumberBox" || TypeName == "DatePicker" || TypeName == "TimePicker" || TypeName == "ComboBox";
            case "TextWrapping":
                return TypeName == "TextBox" || TypeName == "TextBlock" || TypeName == "RichEditBox";
            case "Text":
                return TypeName == "TextBlock" || TypeName == "TextBox" || TypeName == "PasswordBox" || TypeName == "RichEditBox" || TypeName == "AutoSuggestBox";
            case "Content":
                return TypeName == "Button" || TypeName == "CheckBox" || TypeName == "RadioButton" || TypeName == "ToggleButton" || TypeName == "HyperlinkButton" || TypeName == "Expander";
            case "IsChecked":
                return TypeName == "CheckBox" || TypeName == "RadioButton" || TypeName == "ToggleButton";
            case "IsOn":
            case "OnContent":
            case "OffContent":
                return TypeName == "ToggleSwitch";
            case "GroupName":
                return TypeName == "RadioButton";
            case "IsDefault":
            case "IsCancel":
                return TypeName == "Button";
            case "ClickMode":
                return TypeName == "Button" || TypeName == "HyperlinkButton" || TypeName == "ToggleButton" || TypeName == "RepeatButton";
            case "Command":
            case "CommandParameter":
                return TypeName == "Button" || TypeName == "HyperlinkButton" || TypeName == "ToggleButton" || TypeName == "RepeatButton";
            case "IsIndeterminate":
                return TypeName == "ProgressBar" || TypeName == "ProgressRing";
            case "DateFormat":
                return TypeName == "DatePicker" || TypeName == "CalendarDatePicker";
            case "NumberFormat":
                return TypeName == "NumberBox";
            case "FontFamily":
            case "FontStyle":
                return TypeName != "Image" && TypeName != "ProgressRing";
            case "TextAlignment":
                return TypeName == "TextBlock" || TypeName == "TextBox" || TypeName == "PasswordBox" || TypeName == "RichEditBox" || TypeName == "AutoSuggestBox";
            case "Minimum":
            case "Maximum":
            case "Value":
                return TypeName == "Slider" || TypeName == "ProgressBar" || TypeName == "NumberBox";
            case "Orientation":
                return TypeName == "Slider" || TypeName == "ProgressBar" || TypeName == "ProgressRing";
            case "SelectedIndex":
                return TypeName == "ComboBox" || TypeName == "ListView" || TypeName == "NavigationView" || TypeName == "TabView";
            case "IsEditable":
                return TypeName == "ComboBox" || TypeName == "AutoSuggestBox";
            case "AcceptsReturn":
            case "IsReadOnly":
            case "MaxLength":
                return TypeName == "TextBox" || TypeName == "PasswordBox" || TypeName == "RichEditBox";
            case "DisplayMemberPath":
                return TypeName == "ComboBox";
            case "ItemsPanel":
                return TypeName == "ListView" || TypeName == "ListBox" || TypeName == "ItemsRepeater";
            case "Visibility":
            case "IsEnabled":
            case "IsTabStop":
            case "IsHitTestVisible":
                return true;
            case "FontSize":
            case "FontWeight":
            case "Foreground":
                return TypeName != "Image" && TypeName != "ProgressBar" && TypeName != "ProgressRing";
            case "Background":
            case "BorderBrush":
            case "BorderThickness":
            case "CornerRadius":
                return TypeName != "Image" && TypeName != "TextBlock" && TypeName != "ProgressRing";
            default:
                return true;
        }
    }

    public ControlNode Clone() => new()
    {
        Id = Id,
        SourceKey = SourceKey,
        NamespaceUri = NamespaceUri,
        TypeName = TypeName,
        XName = XName,
        Content = Content,
        Row = Row,
        Column = Column,
        RowSpan = RowSpan,
        ColumnSpan = ColumnSpan,
        Width = Width,
        Height = Height,
        HorizontalAlignment = HorizontalAlignment,
        VerticalAlignment = VerticalAlignment,
        OffsetX = OffsetX,
        OffsetY = OffsetY,
        DesignerPositionCustomized = DesignerPositionCustomized,
        Dock = Dock,
        EventName = EventName,
        EventKind = EventKind,
        EventWasAutoGenerated = EventWasAutoGenerated,
        Properties = new Dictionary<string, string>(Properties, StringComparer.Ordinal),
        ExtraAttributes = new Dictionary<string, string>(ExtraAttributes, StringComparer.Ordinal)
    };
}

public sealed class GridDocument
{
    public string FilePath { get; set; } = "";
    public string? CodeBehindPath { get; set; }
    public string RootTypeName { get; set; } = "Grid";
    public int Rows { get; set; } = 1;
    public int Columns { get; set; } = 1;
    public string? XClass { get; set; }
    public string? RootXName { get; set; }
    public bool IsDirty { get; set; }
    public int IgnoredElementCount { get; set; }
    public bool GridSizingSupported { get; set; } = true;
    public string? OriginalXamlText { get; set; }
    public Dictionary<string, string> RootProperties { get; set; } = new(StringComparer.Ordinal);
    public List<ControlNode> Nodes { get; } = new();

    public GridDocument Clone()
    {
        var copy = new GridDocument
        {
            FilePath = FilePath,
            CodeBehindPath = CodeBehindPath,
            RootTypeName = RootTypeName,
            Rows = Rows,
            Columns = Columns,
            XClass = XClass,
            RootXName = RootXName,
            IsDirty = IsDirty,
            IgnoredElementCount = IgnoredElementCount,
            GridSizingSupported = GridSizingSupported,
            OriginalXamlText = OriginalXamlText,
            RootProperties = new Dictionary<string, string>(RootProperties, StringComparer.Ordinal)
        };
        copy.Nodes.AddRange(Nodes.Select(n => n.Clone()));
        return copy;
    }

    public void CopyFrom(GridDocument other)
    {
        FilePath = other.FilePath;
        CodeBehindPath = other.CodeBehindPath;
        RootTypeName = other.RootTypeName;
        Rows = other.Rows;
        Columns = other.Columns;
        XClass = other.XClass;
        RootXName = other.RootXName;
        IsDirty = other.IsDirty;
        IgnoredElementCount = other.IgnoredElementCount;
        GridSizingSupported = other.GridSizingSupported;
        OriginalXamlText = other.OriginalXamlText;
        RootProperties = new Dictionary<string, string>(other.RootProperties, StringComparer.Ordinal);
        Nodes.Clear();
        Nodes.AddRange(other.Nodes.Select(n => n.Clone()));
    }

    public void Normalize()
    {
        Rows = Math.Max(1, Rows);
        Columns = Math.Max(1, Columns);
        foreach (var node in Nodes)
        {
            node.Row = Math.Clamp(node.Row, 0, Rows - 1);
            node.Column = Math.Clamp(node.Column, 0, Columns - 1);
            node.RowSpan = Math.Clamp(node.RowSpan, 1, Rows - node.Row);
            node.ColumnSpan = Math.Clamp(node.ColumnSpan, 1, Columns - node.Column);
        }
    }
}
